spring:
  application:
    name: match-friends-backend
  datasource:
    url: jdbc:mysql://localhost:3306/match_friends?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # ??????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # ?? SQL?????
  global-config:
    db-config:
      id-type: assign_id          # ???? ID
      logic-delete-field: isDeleted
      logic-not-delete-value: 0
      logic-delete-value: 1
